---
name: Checks
on: [push]
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Linter
        run: docker compose run --rm app sh -c "flake8"
      - name: Run Unit Tests
        run: docker compose run --rm app sh -c "python manage.py test"